dist: xenial
language: python
python:
  - 3.7.2
install:
  - pip install -r requirements.txt
  - pip install coveralls 
  - pip install nose
services:
  - postgresql
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - psql -c "CREATE DATABASE test_flight_booking;" -U postgres
script:
  - nosetests --with-coverage --cover-package=app
  - ./cc-test-reporter before-build
after_success:
  - coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info